name: Habits API CI

on:
  push:
    branches:
      - master
    paths:
      - "api/**"

jobs:
  build:
    name: Build and Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Deploy API to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.API_SERVER_SSH_KEY }}
          ARGS: "-rltvz --no-perms --no-owner --no-group"
          SOURCE: "./api/"
          TARGET: ${{ secrets.API_REMOTE_TARGET }}
          REMOTE_HOST: ${{ secrets.API_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.API_REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.API_REMOTE_PORT }}
          EXCLUDE: "/.git/,.docker/,bin/,tests/,docker-compose.yml,.dockerignore,.env.example,GEMINI.md,README.md,vendor/,.env,.idea/,.vscode/,logs/,config/keys/,tools/,docs/,storage/"
